### PR TITLE
Feat/render option

### PR DESCRIPTION
**Pull request by indatawetrust**

### CODE REVIEW

**Comment by cx690** [comment]
In this way maybe make propsType error.
```js
    const TestRender = Loadable({
      loader: () => import("./TestComponent"),
      loading: ({ isError }) => (isError ? "failed" : "wait"),
      render(loaded, props) {
        const Component = loaded;
        const ref = props.forwardRef || undefined;

        return <Component {...props} ref={ref} />;
      },
    });

    const ForwardRefTest = () => {
      const ref = useRef();

      return (
        <div>
         // props forwardRef is not actually TestComponent's props
          <TestRender forwardRef={ref} />
        </div>
      );
    };
```

**Comment by cx690** [comment]
add ref feature at here [https://github.com/cx690/react-loadable/commit/38fc46c92c79ab8c78ce00a06c7cc72aadfd023e](https://github.com/cx690/react-loadable/commit/38fc46c92c79ab8c78ce00a06c7cc72aadfd023e)

**Comment by cx690** [comment]
# use it get ref
ref.current.getRef();

```js
//app.tsx
import Loadable from '@caixue/react-loadable';
import React, { useEffect, useRef } from 'react';
const MyInput = Loadable(() => import('./myInput'));

const App: React.FC = () => {
    const myInput = useRef() as React.MutableRefObject<React.ElementRef<typeof MyInput>>;
    useEffect(() => {
        myInput.current.getRef().then((input) => {
            input.current.focus();
        })
    })
    return <MyInput ref={myInput} />
}

export default App;

//myInput.tsx
import React, { forwardRef, useRef, useImperativeHandle } from 'react';

const MyInput = forwardRef((props, ref) => {
    const input = useRef<HTMLInputElement | null>();
    useImperativeHandle(ref, () => {
        return input;
    })
    return <input ref={(el) => { input.current = el }} />
})

export default MyInput;

```

**Comment by cx690** [comment]
In this way, maybe a batter select , when use the library, user needn't know more about the labrary

**Comment by indatawetrust** [comment]
Thanks for your suggestion. I want to add the package to a project that uses react-loadable (for cra to vite migration). I need a package with the same api as react-loadable. I don't want to make too many changes to the code. Thank you for your support.

**Comment by cx690** [comment]
you are right, I invited you. you can development it  directly.

**Pull request closed without merging**
